project:
  type: book
  output-dir: docs
#  output-dir: ../docs


book:
  title: "Anticipatory Action - Nigeria Flooding"
  author: "OCHA Centre for Humanitarian Data"
  date: "2025-09-23"
  chapters:
    - index.qmd
    - exploration/2025/adamawa_lgas.ipynb

#bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    number-depth: 3
    fig-format: "png" # More efficient than SVG for most plots
    fig-dpi: 96       # Lower DPI for faster rendering
    self-contained: false # Avoid embedding all resources for faster builds
    embed-resources: false
    toc: true          # Enable table of contents for navigation
    css: quarto_assets/custom.css    # Apply the custom CSS globally
    toc-depth: 3
    code-fold: true
    smooth-scroll: true

execute:
  freeze: auto        # Freeze execution to avoid re-running code chunks
  cache: false         # Enable caching for faster re-renders

editor: source
